/**
 * ContextMetricsSection - Token usage, cache efficiency, and context compaction tracking
 */

import { LightBulbIcon } from '@heroicons/react/24/outline'
import { MetricCard } from '../MetricCard.js'
import { MetricSection } from '../MetricSection.js'
import type { SessionMetricsUI } from '../MetricsOverview.js'

interface ContextMetricsSectionProps {
  context: SessionMetricsUI['context']
}

export function ContextMetricsSection({ context }: ContextMetricsSectionProps) {
  if (!context || context.totalInputTokens === undefined || context.totalInputTokens === null) {
    return null
  }

  return (
    <MetricSection
      title="Context Management"
      subtitle="Token usage, cache efficiency, and context compaction tracking"
      icon={<LightBulbIcon />}
    >
      <div className="space-y-4">
        {/* Token Usage Overview */}
        <div className="grid grid-cols-3 gap-3 md:gap-4">
          <MetricCard
            label="Total Input Tokens"
            value={context.totalInputTokens}
            tooltip="Sum of all input tokens sent to API across the entire session"
          />
          <MetricCard
            label="Total Output Tokens"
            value={context.totalOutputTokens}
            tooltip="Sum of all tokens generated by the AI (responses)"
          />
          <MetricCard
            label="Compaction Events"
            value={context.compactEventCount}
            tooltip="Number of times the session hit context limits and required compaction"
            metricId="compaction-events"
          />
        </div>

        <div className="divider text-sm">Context Status</div>

        {/* Context Details */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 md:gap-4">
          <MetricCard
            label="Current Context"
            value={context.contextLength}
            suffix=" tokens"
            tooltip="Current context window size from most recent API call"
          />
          <MetricCard
            label="Context Window"
            value={context.contextWindowSize}
            suffix=" tokens"
            tooltip="The model's own maximum context capacity, resolved per model rather than assumed"
          />
          <MetricCard
            label="Context Usage"
            value={
              context.contextUtilizationPercent
                ? Number.parseFloat(context.contextUtilizationPercent.toString())
                : undefined
            }
            type="percentage"
            tooltip="Current context as percentage of max context window"
            metricId="context-utilization"
          />
          <MetricCard
            label="Avg Tokens/Message"
            value={
              context.avgTokensPerMessage
                ? Number.parseFloat(context.avgTokensPerMessage.toString())
                : undefined
            }
            tooltip="Average input tokens per message"
          />
        </div>

        {/*
         * Cost is rendered only when there IS one, rather than as a set of "N/A"
         * cards. Pricing is server-derived and the desktop app has no price table,
         * so an always-present cost row would read as a permanent gap there instead
         * of what it is: a figure that environment does not compute.
         */}
        {context.apiEquivalentCostUsd != null && (
          <>
            <div className="divider text-sm">Cost</div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 md:gap-4">
              <MetricCard
                label="API-Equivalent Cost"
                value={Number.parseFloat(context.apiEquivalentCostUsd)}
                type="currency"
                tooltip="List-price value of the tokens this session consumed. Not what you were billed - a subscription charges a flat fee regardless."
              />
              <MetricCard
                label="Primary Model"
                value={context.primaryModel ?? undefined}
                type="string"
                tooltip="The model that produced the most output in this session"
              />
              <MetricCard
                label="Models Used"
                value={context.distinctModelCount}
                tooltip="Distinct models this session called"
              />
              {context.providerReportedCostUsd != null && (
                <MetricCard
                  label="Provider Reported"
                  value={Number.parseFloat(context.providerReportedCostUsd)}
                  type="currency"
                  tooltip="The provider's own cost figure, shown as a cross-check against the derived value"
                />
              )}
            </div>

            {/*
             * A partial cost is a FLOOR, and saying so is the whole reason the flag is
             * carried through to the UI. The number without this caveat reads as a total.
             */}
            {context.costHasUnpricedModels && (
              <div className="text-xs text-warning">
                Cost is a floor: no price is held for{' '}
                {context.costUnpricedModels?.length
                  ? context.costUnpricedModels.join(', ')
                  : 'one or more models used here'}
                .
              </div>
            )}
          </>
        )}
      </div>
    </MetricSection>
  )
}
